env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/vue3-essential
  - '@vue/eslint-config-typescript/recommended'
  - '@vue/eslint-config-prettier'
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: 'semi'
        requireLast: true
      singleline:
        delimiter: comma
        requireLast: false
  vue/no-multiple-template-root: 'off'
  vue/multi-word-component-names: 'off'

  'prettier/prettier':
    - error
    - endOfLine: 'auto'
